import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Shield, ArrowLeft, Key } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { authApi, setTokens } from "@/lib/api";
import LoadingOrb from "@/components/LoadingOrb";

export default function MFAVerificationPage() {
  const navigate = useNavigate();
  const [code, setCode] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [user, setUser] = useState(null);

  useEffect(() => {
    // Get user info from localStorage
    const mfaUser = localStorage.getItem('mfa_user');
    const mfaSessionToken = localStorage.getItem('mfa_session_token');
    
    if (!mfaUser || !mfaSessionToken) {
      toast.error("Invalid MFA session. Please try logging in again.");
      navigate('/login');
      return;
    }
    
    setUser(JSON.parse(mfaUser));
  }, [navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (code.length !== 6) {
      toast.error("Please enter a 6-digit code");
      return;
    }

    setIsLoading(true);

    try {
      const mfaSessionToken = localStorage.getItem('mfa_session_token');
      const mfaUser = localStorage.getItem('mfa_user');
      
      console.log('MFA verification attempt:', {
        mfaSessionToken: mfaSessionToken?.substring(0, 20) + '...',
        mfaUser: mfaUser,
        code: code
      });
      
      const response = await authApi.verifyMFA(mfaSessionToken, code);
      
      console.log('MFA verification response:', response);
      
      if (response.access_token) {
        // Store tokens
        setTokens(response);
        
        // Store user data in localStorage for App.jsx to pick up
        localStorage.setItem('phishcatcher_role', response.user.role);
        localStorage.setItem('phishcatcher_email', response.user.email);
        
        // Trigger App.jsx loading state
        window.dispatchEvent(new CustomEvent('auth-success'));
        
        // Clean up MFA session data
        localStorage.removeItem('mfa_session_token');
        localStorage.removeItem('mfa_user');
        localStorage.setItem('terms_consent', 'true');
        
        toast.success("Successfully logged in!");
        
        // Navigate to dashboard
        navigate('/dashboard');
      }
    } catch (error) {
      console.error('MFA verification error:', error);
      toast.error(error.message || "Invalid MFA code. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleResend = () => {
    toast.info("MFA codes are generated by your authenticator app. Please check your app for the latest code.");
  };

  const handleBack = () => {
    // Clean up and go back to login
    localStorage.removeItem('mfa_session_token');
    localStorage.removeItem('mfa_user');
    navigate('/login');
  };

  if (!user) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center p-4 relative overflow-hidden">
        {/* Background Effects */}
        <div className="absolute inset-0 opacity-50" style={{
          background: 'radial-gradient(circle at 50% 40%, rgba(123, 97, 255, 0.08) 0%, #0f172a 70%)'
        }} />
        
        <LoadingOrb size="large" text="Loading..." />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-900 flex items-center justify-center p-4 relative overflow-hidden">
      {/* Background Effects */}
      <div className="absolute inset-0 opacity-50" style={{
        background: 'radial-gradient(circle at 50% 40%, rgba(123, 97, 255, 0.08) 0%, #0f172a 70%)'
      }} />
      
      <div className="relative z-10 w-full max-w-md">
        {/* Back Button */}
        <button
          onClick={handleBack}
          className="mb-6 flex items-center gap-2 text-violet-400 hover:text-violet-300 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Login
        </button>

        {/* Main Card */}
        <div className="glass-card-strong rounded-2xl p-8 border border-violet-500/25">
          {/* Header */}
          <div className="text-center mb-8">
            <div className="w-16 h-16 rounded-xl bg-violet-500/20 flex items-center justify-center mx-auto mb-4">
              <Shield className="w-8 h-8 text-violet-400" />
            </div>
            <h1 className="text-2xl font-bold text-white mb-2">
              Two-Factor Authentication
            </h1>
            <p className="text-gray-400 text-sm">
              Enter the 6-digit code from your authenticator app
            </p>
          </div>

          {/* User Info */}
          <div className="mb-6 p-4 bg-violet-500/10 rounded-xl border border-violet-500/20">
            <p className="text-sm text-gray-400 mb-1">Verifying for:</p>
            <p className="text-white font-medium">{user.email}</p>
            {user.full_name && (
              <p className="text-gray-400 text-sm">{user.full_name}</p>
            )}
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <Label htmlFor="code" className="text-white mb-2 block">
                Authentication Code
              </Label>
              <Input
                id="code"
                type="text"
                value={code}
                onChange={(e) => {
                  // Only allow numbers and max 6 digits
                  const value = e.target.value.replace(/\D/g, '').slice(0, 6);
                  setCode(value);
                }}
                placeholder="000000"
                className="text-center text-2xl tracking-widest bg-slate-800 border-violet-500/25 text-white placeholder-gray-500"
                maxLength={6}
                required
                disabled={isLoading}
              />
            </div>

            <Button
              type="submit"
              className="w-full h-12 bg-violet-600 hover:bg-violet-700 text-white rounded-xl font-medium transition-all duration-200 disabled:opacity-50"
              disabled={isLoading || code.length !== 6}
            >
              {isLoading ? (
                <div className="flex items-center justify-center gap-3">
                  <LoadingOrb size="mini" text="" />
                  <span>Verifying...</span>
                </div>
              ) : (
                <div className="flex items-center justify-center gap-2">
                  <Key className="w-4 h-4" />
                  Verify Code
                </div>
              )}
            </Button>
          </form>

          {/* Help Section */}
          <div className="mt-6 text-center">
            <p className="text-gray-400 text-sm mb-2">
              Can't find your code?
            </p>
            <button
              onClick={handleResend}
              className="text-violet-400 hover:text-violet-300 text-sm transition-colors"
            >
              Check your authenticator app
            </button>
          </div>

          {/* Security Note */}
          <div className="mt-6 p-4 bg-blue-500/10 rounded-xl border border-blue-500/20">
            <div className="flex items-start gap-3">
              <Shield className="w-4 h-4 text-blue-400 mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-blue-400 text-sm font-medium mb-1">
                  Security Notice
                </p>
                <p className="text-gray-400 text-xs">
                  This additional step helps protect your account from unauthorized access.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
