"""Add Gmail integration fields to User model

Revision ID: 20250225_1750_add_gmail_fields
Revises: 20250223_0001_initial_migration
Create Date: 2026-02-25 17:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250225_1750_add_gmail_fields'
down_revision: Union[str, None] = '20250223_0001_initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmail_credentials', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gmail_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gmail_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gmail_auto_scan', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_auto_scan')
    op.drop_column('users', 'gmail_connected_at')
    op.drop_column('users', 'gmail_email')
    op.drop_column('users', 'gmail_credentials')
    # ### end Alembic commands ###
