"""Add MinIO storage fields to analysis_jobs

Revision ID: f448750124b8
Revises: 20250223_0001_initial_migration
Create Date: 2026-03-22 15:51:36.808014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = 'f448750124b8'
down_revision = '20250223_0001_initial_migration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('storage_object_name', sa.String(length=500), nullable=True))
    op.add_column('analysis_jobs', sa.Column('storage_bucket', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_analysis_jobs_user_id'), 'analysis_jobs', ['user_id'], unique=False)
    op.drop_index(op.f('idx_audit_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_user_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_user_id'), table_name='audit_logs')
    op.create_index('idx_audit_action_status_created', 'audit_logs', ['action', 'status', 'created_at'], unique=False)
    op.create_index('idx_audit_ip_created', 'audit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index('idx_audit_status_created', 'audit_logs', ['status', 'created_at'], unique=False)
    op.create_index('idx_audit_user_action_created', 'audit_logs', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index('idx_audit_user_action_status_created', 'audit_logs', ['user_id', 'action', 'status', 'created_at'], unique=False)
    op.create_index('idx_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_user_status_created', 'audit_logs', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_providers_user_id'), 'email_providers', ['user_id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('password_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_password_history_created_at'), table_name='password_history')
    op.drop_index(op.f('idx_password_history_user_id'), table_name='password_history')
    op.drop_constraint(op.f('password_history_user_id_fkey'), 'password_history', type_='foreignkey')
    op.create_foreign_key(None, 'password_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_user_account_status'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_email_active', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_account_status'), 'users', ['account_status'], unique=False)
    op.drop_constraint(None, 'password_history', type_='foreignkey')
    op.create_foreign_key(op.f('password_history_user_id_fkey'), 'password_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_password_history_created_at'), 'password_history', ['created_at'], unique=False)
    op.alter_column('password_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_email_providers_user_id'), table_name='email_providers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_status_created', table_name='audit_logs')
    op.drop_index('idx_audit_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_user_action_status_created', table_name='audit_logs')
    op.drop_index('idx_audit_user_action_created', table_name='audit_logs')
    op.drop_index('idx_audit_status_created', table_name='audit_logs')
    op.drop_index('idx_audit_ip_created', table_name='audit_logs')
    op.drop_index('idx_audit_action_status_created', table_name='audit_logs')
    op.create_index(op.f('idx_audit_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_user_action'), 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('idx_audit_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('idx_audit_action'), 'audit_logs', ['action'], unique=False)
    op.drop_index(op.f('ix_analysis_jobs_user_id'), table_name='analysis_jobs')
    op.drop_column('analysis_jobs', 'storage_bucket')
    op.drop_column('analysis_jobs', 'storage_object_name')
    # ### end Alembic commands ###
